---
title: "Ryan S. Laird's CV"
author: Ryan S. Laird
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "./data/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)

cat("Above network graph shows connections between experiences.")
```


```{r}

if(params$pdf_mode){
  cat("View this CV online with links at https://ryanvidegar-laird.github.io/CV/laird_cv.html")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://ryanvidegar-laird.github.io/CV/laird_cv.pdf)")
}
```


Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with R packages [**pagedown**](https://github.com/rstudio/pagedown) and [**datadrivencv**](https://github.com/nstrayer/datadrivencv). 

The source code is available on [GitHub](https://github.com/RyanVidegar-Laird/CV).

Last updated on `r Sys.Date()`.



Main
================================================================================

Ryan S. Laird {#title}
--------------------------------------------------------------------------------

```{r, include=FALSE}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('professional_experience')
```

<br>
<br>
<br>

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Publications, Talks, and Posters {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('pubs')
```


```{r}
CV %<>% print_links()
```

